import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "../globals.css";
import { Layout } from "antd";
import Sidebar from "@/components/common/Sidebar";
import { Content } from "antd/es/layout/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ padding: 0, margin: 0 }}>
        <Layout className="h-screen">
          <Sidebar />
          <Layout>
            <Content>
              <AntdRegistry>{children}</AntdRegistry>
            </Content>
          </Layout>
        </Layout>
      </body>
    </html>
  );
}
